version: "2"
services:
  mamute:
    image: codemedic/mamute
    environment:
      MYSQL_PASSWORD: letmein
    ports:
      - "8090:80"
      - "8091:8080"
    links:
      - mysql
  mysql:
    image: "mysql:5.6"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: letmein
      MYSQL_DATABASE: mamute
      MYSQL_USER: mamute
      MYSQL_PASSWORD: letmein
    expose:
      - "3306"
volumes:
  mysql-data:

#  vim: set tabstop=2 shiftwidth=2 expandtab :
